# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Go.gitlab-ci.yml

image: golang:latest

stages:
  - build
  - test


compile:
  stage: build
  before_script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - wget https://github.com/upx/upx/releases/download/v4.2.4/upx-4.2.4-amd64_linux.tar.xz && tar -zxvf upx-4.2.4-amd64_linux.tar.xz && cd tar -zxvf upx-4.2.4-amd64_linux && mv upx /usr/local/bin
    - mkdir -p cmd
    
  script:
    - make build_backend upx_bin
  artifacts:
    paths:
      - emotionalBeach

      
# deploy:
#   stage: deploy
#   script: echo "Define your deployment script!"
#   environment: production
