// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"emotionalBeach/config"
	"emotionalBeach/internal/dao"
	"emotionalBeach/internal/server"
)

// Injectors from wire.go:

//go:generate wire
func InitializeApp() (*server.Server, error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, err
	}
	database, err := dao.NewDatabase(configConfig)
	if err != nil {
		return nil, err
	}
	serverServer, err := server.NewServer(configConfig, database)
	if err != nil {
		return nil, err
	}
	return serverServer, nil
}
