// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"emotionalBeach/config"
	"emotionalBeach/internal/dao"
	"emotionalBeach/internal/infra"
	"emotionalBeach/internal/server"
	"emotionalBeach/internal/service"
)

// Injectors from wire.go:

// InitializeApp is the Wire injector.
// Wire reads this function signature, resolves the provider graph, and writes
// the concrete implementation into wire_gen.go.
func InitializeApp(cfg *config.Config) (*App, func(), error) {
	db, cleanup, err := infra.ProvideDB(cfg)
	if err != nil {
		return nil, nil, err
	}
	daoDao := dao.New(db)
	client, cleanup2, err := infra.ProvideRedis(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	serviceService := service.New(cfg, daoDao, db, client)
	loggers, cleanup3, err := infra.ProvideLoggers(cfg)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	httpServer := server.New(cfg, serviceService, loggers)
	app := NewApp(cfg, httpServer, db, client, loggers)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
