// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"emotionalBeach/config"
	"emotionalBeach/internal/handler/github"
	"emotionalBeach/internal/handler/health"
	"emotionalBeach/internal/handler/relation"
	"emotionalBeach/internal/handler/user"
	"emotionalBeach/internal/handler/webhook"
	"emotionalBeach/internal/infra/db"
	"emotionalBeach/internal/infra/logger"
	"emotionalBeach/internal/repository/relation"
	"emotionalBeach/internal/repository/user"
	"emotionalBeach/internal/server"
	"emotionalBeach/internal/service/github"
	"emotionalBeach/internal/service/health"
	"emotionalBeach/internal/service/notification"
	"emotionalBeach/internal/service/relation"
	"emotionalBeach/internal/service/user"
)

// Injectors from wire.go:

// InitializeApp is the Wire injector.
// Wire reads this function signature, resolves the provider graph, and writes
// the concrete implementation into wire_gen.go.
func InitializeApp(cfg *config.Config) (*App, func(), error) {
	loggers, cleanup, err := logger.ProvideLoggers(cfg)
	if err != nil {
		return nil, nil, err
	}
	gormDB, cleanup2, err := db.ProvideDB(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	gormRepo := userrepo.NewGormRepo(gormDB)
	svc := usersvc.NewSvc(gormRepo)
	handler := userhandler.NewHandler(svc)
	relationrepoGormRepo := relationrepo.NewGormRepo(gormDB)
	relationsvcSvc := relationsvc.NewSvc(relationrepoGormRepo, gormRepo)
	relationhandlerHandler := relationhandler.NewHandler(relationsvcSvc)
	githubsvcSvc := githubsvc.NewSvc(cfg)
	githubhandlerHandler := githubhandler.NewHandler(githubsvcSvc)
	client, cleanup3, err := db.ProvideRedis(cfg)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	healthsvcSvc := healthsvc.NewSvc(gormDB, client)
	healthhandlerHandler := healthhandler.NewHandler(healthsvcSvc)
	emailSender := notification.NewEmailSender(cfg)
	webhookhandlerHandler := webhookhandler.NewHandler(emailSender)
	engine := server.NewRouter(cfg, loggers, handler, relationhandlerHandler, githubhandlerHandler, healthhandlerHandler, webhookhandlerHandler)
	httpServer := server.NewHTTPServer(cfg, engine)
	app := NewApp(cfg, httpServer, gormDB, client, loggers)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
