basePath: /
definitions:
  models.LoginRequest:
    properties:
      password:
        example: admin
        type: string
      username:
        example: admin
        type: string
    required:
    - password
    - username
    type: object
info:
  contact:
    name: Eric Jiang
    url: http://www.swagger.io/support
  description: |-
    ```
    Development Environment :go v1.23.7 + gin v1.10.1 + gorm v1.30.2 + viper v1.20.1
    ```
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: 情感沙滩API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: 根据用户名、密码获取授权码
      parameters:
      - description: 登录参数
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses: {}
      summary: 登陆获取Token
      tags:
      - 注册登陆
  /register:
    post:
      consumes:
      - multipart/form-data
      description: 根据名称、密码、二次密码、手机号、邮箱(可选)注册
      parameters:
      - description: Name
        in: formData
        name: name
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      - description: repeat_password
        in: formData
        name: repeat_password
        required: true
        type: string
      - description: Phone
        in: formData
        name: phone
        required: true
        type: string
      - description: EMAIL
        in: formData
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 创建用户
      tags:
      - 注册登陆
  /v1/relation/add:
    post:
      description: 通过昵称加好友
      parameters:
      - description: 增加的用户id
        in: formData
        name: userId
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: 通过昵称加好友
      tags:
      - 好友关系
  /v1/relation/list:
    post:
      description: 批量获取好友列表信息
      parameters:
      - description: 好友ID
        in: formData
        name: userId
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: 获取好友列表
      tags:
      - 好友关系
  /v1/user/condition:
    get:
      description: 批量获取所有用户信息
      parameters:
      - description: ID
        in: query
        name: id
        type: string
      - description: 手机号
        in: query
        name: phone
        type: string
      - description: Email
        in: query
        name: email
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: 获取所有用户
      tags:
      - 用户
  /v1/user/delete:
    delete:
      description: 更新用户信息
      parameters:
      - description: ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: 更新用户信息
      tags:
      - 用户
  /v1/user/list:
    get:
      description: 批量获取所有用户信息
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: 获取所有用户
      tags:
      - 用户
  /v1/user/update:
    post:
      description: 更新用户信息
      parameters:
      - description: ID
        in: formData
        name: id
        required: true
        type: string
      - description: 用户名
        in: formData
        name: name
        type: string
      - description: 密码
        in: formData
        name: password
        type: string
      - description: 手机号
        in: formData
        name: phone
        type: string
      - description: Email
        in: formData
        name: email
        type: string
      - description: avatar
        in: formData
        name: avatar
        type: string
      - description: gender
        in: formData
        name: gender
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: 更新用户信息
      tags:
      - 用户
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
